# shhrdgs
I have a problem with instabot please help me$ python3 hackinsta.py Please enter a username: shhrdgs Traceback (most recent call last):   File "hackinsta.py", line 142, in &lt;module>     instabrute = Instabrute(Input('Please enter a username: '))   File "hackinsta.py", line 34, in __init__     self.loadPasswords()   File "hackinsta.py", line 48, in loadPasswords     self.passwords = f.read().splitlines()   File "/data/data/com.termux/files/usr/lib/python3.7/codecs.py", line 322, in decode     (result, consumed) = self._buffer_decode(data, self.errors, final) UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 4054309: invalid continuation byte $
